#!/bin/bash

# Cloudflare Pages Deployment Fix
# This script helps identify and fix the Cloudflare Pages deployment configuration

echo "=========================================="
echo "Cloudflare Pages Deployment Configuration"
echo "=========================================="
echo ""
echo "Your build is working correctly! ✓"
echo "Build time: ~1m 18s"
echo "Build output: ./build/client"
echo ""
echo "❌ PROBLEM:"
echo "Your Cloudflare Pages project is configured with the WRONG deployment command:"
echo "  Current: npx wrangler versions upload (Workers command)"
echo "  Should be: (empty/none for automatic Pages deployment)"
echo ""
echo "=========================================="
echo "FIX STEPS - CLOUDFLARE PAGES DASHBOARD"
echo "=========================================="
echo ""
echo "1. Go to: https://dash.cloudflare.com/"
echo ""
echo "2. Navigate to: Workers & Pages → Your Project (bolt)"
echo ""
echo "3. Click: Settings → Builds & deployments"
echo ""
echo "4. Find the 'Build command' section and set:"
echo "   Build command: npm run build"
echo "   (or: pnpm run build)"
echo ""
echo "5. Set 'Build output directory':"
echo "   Build output directory: build/client"
echo ""
echo "6. IMPORTANT - Check 'Deploy command' or 'Custom deploy command':"
echo "   If you see a field for 'Deploy command' or similar,"
echo "   REMOVE or DELETE the following if present:"
echo "     ❌ npx wrangler versions upload"
echo "     ❌ wrangler versions upload"
echo ""
echo "   Leave it EMPTY or set it to:"
echo "     ✓ (empty/none)"
echo ""
echo "   OR if you must have a deploy command, use:"
echo "     ✓ npx wrangler pages deploy ./build/client"
echo ""
echo "7. Environment Variables (optional but recommended):"
echo "   Add: NODE_OPTIONS = --max-old-space-size=8192"
echo ""
echo "8. Click 'Save' and trigger a new deployment"
echo ""
echo "=========================================="
echo "ALTERNATIVE: DEPLOY MANUALLY"
echo "=========================================="
echo ""
echo "You can also deploy directly from your local machine:"
echo ""
echo "  npm run build"
echo "  npx wrangler pages deploy ./build/client --project-name=bolt"
echo ""
echo "Or use the provided script:"
echo ""
echo "  ./deploy-cloudflare.sh"
echo ""
echo "=========================================="
echo ""
echo "For more information, see: CLOUDFLARE_DEPLOYMENT.md"
echo ""
